services:
  app:
    image: ${ECR_IMAGE}
    restart: unless-stopped
    entrypoint: ["/var/www/html/docker/app_entry.sh"]
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - closet_network

  web:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      - NGINX_HOST=${NGINX_HOST:-localhost}
    volumes:
      - ./docker/nginx.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - closet_network

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - closet_network

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - closet_network

  queue:
    image: ${ECR_IMAGE}
    restart: unless-stopped
    entrypoint: ["php", "artisan", "queue:work", "redis", "--sleep=3", "--tries=3", "--timeout=60"]
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - closet_network

volumes:
  db_data:

networks:
  closet_network:
