version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: clozit_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    ports:
      - "${APP_PORT:-9000}:9000"
    entrypoint: [ "/var/www/html/docker/app_entry.sh" ]
    networks:
      - laravel_network
    depends_on:
      - db
      - redis
      - node

  web:
    image: nginx:alpine
    container_name: clozit_nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${WEB_PORT:-8080}:80"
    networks:
      - laravel_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: clozit_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    networks:
      - laravel_network

  redis:
    image: redis:alpine
    container_name: clozit_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - laravel_network

  node:
    image: node:18-alpine
    container_name: clozit_node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
